var bankdata =
{
    "bon":{
        "bankname":"宁波银行",
        "bankid":"bon",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"宁波银行",
                "links": "javascript:goCards()"
            }
        ],
        "cards":[
            {
                "image":"img/banks/card/bon01.png",
                "name":"Visa环球卡",
                "shortname":"Visa环球卡",
                "detail":"",
                "pop":"bank16-card1.jpg",
                "scroll": "1",
                "bankname":"宁波银行",
                "id":1,
                "link":"https://aapw.nbcb.com.cn/mobilebank/page/vueArea/vVueCredit/creditSPA.html#/applyProcess?useQuery=true&cardCode=0061&tab=pageB&channelNo=23&paramSource=url"
            },
        ]
    },
    "bob":{
        "bankname":"北京银行",
        "bankid":"bob",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"北京银行",
                "links": "javascript:goCards()"
            }
        ],
        "cards":[
            {
                "image":"img/banks/card/bob01.png",
                "name":"Visa白金卡 ",
                "shortname":"Visa白金卡 ",
                "detail":"",
                "pop":"bank15-card1.jpg",
                "scroll": "0",
                "bankname":"北京银行",
                "id":1,
                "link":"https://card.bankofbeijing.com.cn/coas/second/mb/card?cardPrdCd=0105&mobilePhone=&rcmmndStffId=&saleMan="
            },
        ]
    },
    "boc":{
        "bankname":"中行",
        "bankid":"boc",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"中国银行",
                "links": "javascript:goCards()"
            }
        ],
        "cards":[
            {
                "image":"img/banks/card/boc01@2x.png",
                "name":"卓隽留学Visa美元卡",
                "shortname":"卓隽留学<br/>Visa美元卡",
                "detail":"开卡即送新东方在线精品出国课程，12月31日前申请还可免年费",
                "pop":"bank3-card2.jpg",
                "scroll": "0",
                "bankname":"中行",
                "id":1,
                "link":"https://apply.mcard.boc.cn/apply/mobile/product/productConfirm/mchot?newInTypeCode=57719d33301ab5a878f0d77d9ae213400820c14219f3b1b93ac6d00588ebf866abb404bafb771befa0778702915ad7bfe74b49702e2cef88fd39d0fd943bc39beee36686df1e21f1bd78250ad991321052e2b01468a2b466f5749eaf088c8403b356cb2f6194cc7700bb319719673d750b610b80930fafdb6b95da2bbb5e81e2&masterOrSubFlag=1&formVersion=GPB1A&shortId=bqAfum&channelSource=1"
            },
            {
                "image":"img/banks/card/boc02@2x-84.png?1",
                "name":"长城卓隽新东方金卡（Visa金）",
                "shortname":"长城卓隽<br/>新东方金卡",
                "detail":"12月31日前申请，威士品牌免年费，银联品牌免首年年费",
                "pop":"bank3-card3.jpg?1",
                "scroll": "0",
                "bankname":"中行",
                "id":2,
                "link":"https://apply.mcard.boc.cn/apply/mobile/product/productListPage/proList?bizUuid=3ce20ee0cef0c6838c75bc4ed2b24ae78c979dcbcb90818967254c10641031908cd58c1fd52f87a4ec35222fb39cefb77b4fee55e36cae5c94da0f56bf5b00aa157d1257c075a461f637892493a76effa035303668ee35e3ad58f82f97846b844cf5a10bf00c283a0dbb867c800583b842048b41f60b899d85d01ae22cf30868,73f57c8c5bf5b2d79b23da53a1c408b97a8cd7cc3809faeae41324612447b1a76cfcf1f7b7379ab3e0a3b93c5df413fce1a29a62dec36e16f25371aec9b02ac5fb78693653190cd515ecb2974f160483595ddd98d029530e8005de496da18a61d4e8e26b77b0940622f5ec42e057ea389e0973c0e949e03f60a36660c8f6dfe9"
            },
            {
                "image":"img/banks/card/boc03@2x-84.png",
                "name":"长城卓隽新东方白金卡（Visa白金）",
                "detail":"12月31日前申请，威士品牌免年费，银联品牌免首年年费",
                "pop":"bank3-card4.jpg?1",
                "scroll": "0",
                "shortname":"长城卓隽<br/>新东方白金卡",
                "bankname":"中行",
                "id":3,
                "link":"https://apply.mcard.boc.cn/apply/mobile/product/productListPage/proList?bizUuid=3ce20ee0cef0c6838c75bc4ed2b24ae78c979dcbcb90818967254c10641031908cd58c1fd52f87a4ec35222fb39cefb77b4fee55e36cae5c94da0f56bf5b00aa157d1257c075a461f637892493a76effa035303668ee35e3ad58f82f97846b844cf5a10bf00c283a0dbb867c800583b842048b41f60b899d85d01ae22cf30868,73f57c8c5bf5b2d79b23da53a1c408b97a8cd7cc3809faeae41324612447b1a76cfcf1f7b7379ab3e0a3b93c5df413fce1a29a62dec36e16f25371aec9b02ac5fb78693653190cd515ecb2974f160483595ddd98d029530e8005de496da18a61d4e8e26b77b0940622f5ec42e057ea389e0973c0e949e03f60a36660c8f6dfe9"
            },
            {
                "image":"img/banks/card/boc04@2x.png",
                "name":"长城卓隽留学欧元卡",
                "shortname":"长城卓隽<br/>留学欧元卡",
                "detail":"开卡即送新东方在线精品出国课程，12月31日前申请还可免年费",
                "pop":"bank3-card5.jpg",
                "scroll": "0",
                "bankname":"中行",
                "id":4,
                "link":"https://apply.mcard.boc.cn/apply/mobile/product/productConfirm/mchot?newInTypeCode=7437dc040a134a31156c64a5969a1a9ff53ce538984d1efda59e70101e5a43af0907da38df7ab17e0ab3b4cbb7dc1263af68b8844a8d6ae45c7513944e774db05bd1135d1631db88d96509e93cad24a9c5540a22bb1a72aaafa52e708ba1bedf9b5dd44716c32b8589dc98d17caee1cd9e822321c172245aea81fc68057f219d&masterOrSubFlag=1&formVersion=GPB1A&shortId=RJFbuu&channelSource=1"
            }
        ]
    },
    "boc_debit":{
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"中国银行",
                "links": "javascript:goCards()"
            },
            {
                "image":"img/banks/top_banner/bank_boc_debit@2x.png",
                "desc":"中国银行",
            }
        ],
        "cards":[
            {
                "image":"img/banks/card/boc_debit04@2x.png",
                "name":"Visa冬奥借记卡（黑卡）",
                "shortname":"Visa冬奥<br/>借记卡（黑卡）",
                "detail":"境外消费笔笔返现1%，更有全球知名雪场低至7折起等礼遇",
                "pop":"bank3-card6.jpg",
                "scroll": "0",
                "bankname":"中行Debit",
                "id":1,
                "linkdesc":"如需办卡，请前往中国银行网点咨询"
            },
            {
                "image":"img/banks/card/boc_debit03@2x.png",
                "name":"Visa冬奥借记卡（蓝卡）",
                "shortname":"Visa冬奥<br/>借记卡（蓝卡）",
                "detail":"境外消费笔笔返现1%，更有全球知名雪场低至7折起等礼遇",
                "pop":"bank3-card7.jpg",
                "scroll": "0",
                "bankname":"中行Debit",
                "id":2,
                "linkdesc":"如需办卡，请前往中国银行网点咨询"
            },
            {
                "image":"img/banks/card/boc_debit02@2x.png",
                "name":"Visa跨境通国际借记卡（白金卡）",
                "shortname":"Visa跨境通国际<br/>借记卡（白金卡）",
                "detail":"留学服务费立减高达2000元，精选海淘商户笔笔返现10%",
                "pop":"bank3-card8.jpg",
                "scroll": "0",
                "bankname":"中行Debit",
                "id":3,
                "linkdesc":"如需办卡，请前往中国银行网点咨询"
            },
            {
                "image":"img/banks/card/boc_debit01@2x.png",
                "name":"Visa跨境通国际借记卡（金卡）",
                "shortname":"Visa跨境通国际<br/>借记卡（金卡）",
                "detail":"高达30万元留学生保障计划，精选海淘商户笔笔返现10%",
                "pop":"bank3-card9.jpg",
                "scroll": "0",
                "bankname":"中行Debit",
                "id":4,
                "linkdesc":"如需办卡，请前往中国银行网点咨询"
            }
        ]
    },
    "nh":{
        "bankname":"农行",
        "bankid":"abc",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"农业银行",
                "links": "javascript:goCards()"
            },
            {
                "image":"img/banks/top_banner/bank_nh@2x.png",
                "desc":"中国农业银行",
                "link":"https://wx.abchina.com/CreditCard/netBank/webank/applyCard.aspx?id=&q=direct&cardcode=VCPC1I"
            }
        ],
        "cards":[
            {
                "image":"img/banks/card/nh01@2x.png",
                "name":"留学白金信用卡（美好生活版）",
                "shortname":"留学白金信用卡<br/>（美好生活版）",
                "detail":"刷卡免国际结算费，更可享1元起境外接送机福利",
                "pop":"bank2-card1.jpg",
                "scroll": "0",
                "bankname":"农行",
                "id":1,
                "link":"https://wx.abchina.com/CreditCard/netBank/webank/applyCard.aspx?id=null&q=direct&cardcode=VCPC1I"
            },
            {
                "image":"img/banks/card/nh02@2x.png",
                "name":"留学白金信用卡（诗情画意版）",
                "shortname":"留学白金信用卡<br/>（诗情画意版）",
                "detail":"刷卡免国际结算费，更可享1元起境外接送机福利",
                "pop":"bank2-card2.jpg",
                "scroll": "0",
                "bankname":"农行",
                "id":2,
                "link":"https://wx.abchina.com/CreditCard/netBank/webank/applyCard.aspx?id=null&q=direct&cardcode=VCPC1I"
            }
        ]
    },
    "gf":{
        "bankname":"广发",
        "bankid":"cgb",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"广发银行",
                "links": "javascript:goCards()"
            },
            {
                "image":"img/banks/top_banner/bank_gf@2x.png",
                "desc":"广发银行",
                "link":"https://wap.cgbchina.com.cn/mbcreditCardApply/#/mbcreditCardApply/creditCard0?seqno=zHxf0wvcQPUtyepsRTuf-SdbbD_99_B9B11_a9_Bb&ACTIVITY_ID=6ZTfwRdeQSPy-fscp1b4B915BBBBm"
            }
        ],
        "cards":[
            {
                "image":"img/banks/card/gf01@2x.png",
                "name":"鼎极Visa无限卡",
                "shortname":"鼎极Visa无限卡",
                "detail":"现在办卡，尊享境内外贵宾礼遇",
                "pop":"bank9-card1.jpg",
                "scroll": "0",
                "bankname":"广发",
                "id":1,
                "link":"http://95508.com/zctPrBM0"
            },
            {
                "image":"img/banks/card/gf02@2x.png",
                "name":"Visa无限奥运卡",
                "shortname":"Visa无限奥运卡",
                "detail":"现在办卡，尊享境内外贵宾礼遇",
                "pop":"bank9-card2.jpg",
                "scroll": "0",
                "bankname":"广发",
                "id":2,
                "link":"http://95508.com/zctPrBM0"
            },
            {
                "image":"img/banks/card/gf03@2x.png",
                "name":"Visa臻享白金卡",
                "shortname":"Visa臻享白金卡",
                "detail":"",
                "pop":"bank9-card3.jpg",
                "scroll": "0",
                "bankname":"广发",
                "id":3,
                "link":"https://n.95508.com/HsN6fTHQG"
            },
            {
                "image":"img/banks/card/gf04@2x.png",
                "name":"Visa臻尚白金卡",
                "shortname":"Visa臻尚白金卡",
                "detail":"",
                "pop":"bank9-card4.jpg",
                "scroll": "0",
                "bankname":"广发",
                "id":4,
                "link":"http://xyk.cgbchina.com.cn/subsite/202109/25120158/wap.html"
            }
        ]
    },
    "ph":{
        "bankname":"浦发",
        "bankid":"spdb",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"浦发银行",
                "links": "javascript:goCards()"
            }
        ],
        "cards":[
            {
                "image":"img/credit_card/pufa-new1.png",
                "name":"Visa御玺卡",
                "shortname":"Visa御玺卡",
                "detail":"境外留学缴费最高15%返现全球1%“无封顶”消费返现",
                "pop":"bank10-card1.jpg",
                "scroll": "0",
                "bankname":"浦发",
                "id":1,
                "link":"https://ecentre.spdbccc.com.cn/creditcard/indexActivity.htm?data=P2248092"
            },
            {
                "image":"img/banks/card/ph01@2x.png",
                "name":"Visa超凡白金信用卡",
                "shortname":"Visa超凡<br/>白金信用卡",
                "detail":"新户达标即可享野兽派精美礼品，还有更多达标礼等你解锁",
                "pop":"bank10-card2.jpg",
                "scroll": "0",
                "bankname":"浦发",
                "id":2,
                "link":"https://ecentre.spdbccc.com.cn/creditcard/indexActivity.htm?data=I2803466&wchannel=5"
            },
            {
                "image":"img/banks/card/ph02@2x.png",
                "name":"Visa超凡白金信用卡（臻享版）",
                "shortname":"Visa超凡白金<br/>信用卡（臻享版）",
                "detail":"臻享版专享全球机场贵宾厅、境内机场餐饮",
                "pop":"bank10-card3.jpg",
                "scroll": "0",
                "bankname":"浦发",
                "id":3,
                "link":"https://ecentre.spdbccc.com.cn/creditcard/indexActivity.htm?data=I2803466&wchannel=6"
            },
            {
                "image":"img/banks/card/ph03@2x.png",
                "name":"简约白金卡",
                "shortname":"简约白金卡",
                "detail":"尊享免年费等权益",
                "pop":"bank10-card4.jpg",
                "scroll": "0",
                "bankname":"浦发",
                "id":4,
                "link":"https://ecentre.spdbccc.com.cn/card/indexActivity.htm?data=A2102081141557065382&dataId=c540326e731645678a8b4b6892dc5259"
            }
        ]
    },
    "gh":{
        "bankname":"工行",
        "bankid":"icbc",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"工商银行",
                "links": "javascript:goCards()"
            }
        ],
        "cards":[
            {
                "image":"img/banks/card/gh01@2x.png",
                "name":"Visa留学生白金卡",
                "shortname":"Visa留学生白金卡",
                "detail":"工商银行留学信用卡发行多币贷记卡产品，白金卡和金卡等级，以“1+1”的形式发行。有效期8年。",
                "pop":"bank1-card1.jpg",
                "scroll": "0",
                "bankname":"工行",
                "id":1,
                "link":"https://elife.icbc.com.cn/OFSTCARDWEB/dist/#/apply/detail/460000459/105BKRK0001000000000000000"
            },
            {
                "image":"img/banks/card/gh02@2x.png",
                "name":"Visa留学生金卡",
                "shortname":"Visa留学生金卡",
                "detail":"工商银行留学信用卡发行多币贷记卡产品，白金卡和金卡等级，以“1+1”的形式发行。有效期8年。",
                "pop":"bank1-card2.jpg",
                "scroll": "0",
                "bankname":"工行",
                "id":2,
                "link":"https://elife.icbc.com.cn/OFSTCARDWEB/dist/#/apply/detail/460000460/105BKRK0001000000000000000"
            }
        ]
    },
    "jh":{
        "bankname":"建行credit",
        "bankid":"ccb",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"建设银行",
                "links": "javascript:goCards()"
            }
        ],
        "cards":[
            {
                "image":"img/banks/card/jh01@2x.png",
                "name":"Visa畅享卡",
                "shortname":"Visa畅享卡",
                "detail":"刷卡满200元即享118元返现，还有年费标准、积分等优惠政策",
                "pop":"bank8-card5.jpg",
                "scroll": "0",
                "bankname":"建行credit",
                "id":1,
                "link":"http://m.ccb.com/cn/creditcard/apply/mobile/newMobile/standard_form.html?cardId=20190813_1565683729&applyCity=3&applyProv=1003&Rcmd_insID=W00000001"
            },
            {
                "image":"img/banks/card/jh02@2x.png",
                "name":"Visa全球支付卡",
                "shortname":"Visa全球支付卡",
                "detail":"",
                "pop":"bank8-card6.jpg",
                "bankname":"建行credit",
                "id":2,
                "link":"https://sinfo1.ccb.com/cn/creditcard/apply/new_mobile/index.html?cardId=20200925_1601021147&applyCity=3&applyProv=1003&"
            }
        ]
    },
    "pa":{
        "bankname":"平安",
        "bankid":"pab",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"平安银行",
                "links": "javascript:goCards()"
            }
        ],
        "cards":[
            {
                "image":"img/banks/card/pa01@2x.png",
                "name":"精英白金卡",
                "shortname":"精英白金卡",
                "detail":"商旅人士必备白金卡，享不限次航延险及接送机等礼遇",
                "pop":"bank11-card1.jpg",
                "scroll": "0",
                "bankname":"平安",
                "id":1,
                "link":"https://b.pingan.com.cn/ca/pc/index.html#/First?channel=WX&onlineSQFlag=N&sign=35cfbdc6-a492-4b49-a8f0-c1324973943f09b96ec924c9cd1c072c6832bfe1ad06&ccp=15a21&versionNo=R10310&scc=940000447&bt5=940000447&bt6=WBVS99999WSYSYCP002&mt=WBVS99999WSYSYCP002&deleteCardinfo=Y&simpListAB=null"
            },
            {
                "image":"img/banks/card/pa02@2x.png",
                "name":"美元白金卡",
                "shortname":"美元白金卡",
                "detail":"0货币转换费",
                "pop":"bank11-card2.jpg",
                "scroll": "0",
                "bankname":"平安",
                "id":2,
                "link":"https://bank-static.pingan.com.cn/ca/pc/index.html#/First?channel=WXNC&onlineSQFlag=N&sign=3080a7bb-0f22-41b9-bd03-9b2dd024025b4b36450a52f936b4c7c0844848607357&ccp=21&versionNo=R10310&scc=900000288"
            },
            {
                "image":"img/banks/card/pa03@2x.png",
                "name":"Costco联名卡Visa白金卡",
                "shortname":"Costco联名卡<br/>Visa白金卡",
                "detail":"核卡首3月消费8800元免首年年费",
                "pop":"bank11-card3.jpg",
                "scroll": "0",
                "bankname":"平安",
                "id":3,
                "link":"https://b.pingan.com.cn/creditcard/lp/201906/costcoLmk/index.shtml?url=https%3A%2F%2Fc.pingan.com.cn%2Fca%2Findex%3Fscc%3D940000447%26sign%3D09b96ec924c9cd1c072c6832bfe1ad06%26source%3D940000447%26mt%3DWBVS99999WSYSYCP001%26versionNo%3DR10310%26outerSource%3DWBVS99999WSYSYCP001%26onlineSQFlag%3DN%26channel%3DWX"
            },
            {
                "image":"img/banks/card/pa04@2x.png",
                "name":"Costco联名卡Visa金卡",
                "shortname":"Costco联名卡<br/>Visa金卡",
                "detail":"核卡首3月消费8800元免首年年费",
                "pop":"bank11-card4.jpg",
                "scroll": "0",
                "bankname":"平安",
                "id":4,
                "link":"https://b.pingan.com.cn/creditcard/lp/201906/costcoLmk/index.shtml?url=https%3A%2F%2Fc.pingan.com.cn%2Fca%2Findex%3Fscc%3D940000447%26sign%3D09b96ec924c9cd1c072c6832bfe1ad06%26source%3D940000447%26mt%3DWBVS99999WSYSYCP001%26versionNo%3DR10310%26outerSource%3DWBVS99999WSYSYCP001%26onlineSQFlag%3DN%26channel%3DWX"
            }
        ]
    },
    "gd":{
        "bankname":"光大",
        "bankid":"ceb",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"光大银行",
                "links": "javascript:goCards()"
            },
            {
                "image":"img/banks/top_banner/bank_gd@2x.png",
                "desc":"光大 出国金融信用卡",
                "link":"ceb-detail.php"
            }
        ],
        "cards":[
            {
                "image":"img/banks/card/gd01@2x.png",
                "name":"Evoke联名白金信用卡",
                "shortname":"Evoke联名<br/>白金信用卡",
                "detail":"Visa卡免年费，银联卡新客户首次交易后送688元年费抵扣券",
                "pop":"bank7-card1.jpg",
                "bankname":"光大",
                "scroll": "0",
                "id":1,
                "link":"https://xyk.cebbank.com/icip/icip-applypage/info1?cardId=17553&pro_code=ZHTG03BKRK000001VISA"
            },
            {
                "image":"img/banks/card/gd02@2x.png",
                "name":"Evoke菁英白金联名信用卡",
                "shortname":"Evoke菁英<br/>白金联名信用卡",
                "detail":"首年免年费，交易满6笔免次年年费",
                "pop":"bank7-card2.jpg",
                "scroll": "0",
                "bankname":"光大",
                "id":2,
                "link":"https://xyk.cebbank.com/icip/icip-applypage/info1?cardId=20959&pro_code=ZHTG03BKRK000001VISA"
            },
            {
                "image":"img/banks/card/gd03@2x.png",
                "name":"出国金融信用卡",
                "shortname":"出国金融信用卡",
                "detail":"首年可用10万积分或688年费抵扣券抵扣688元年费",
                "pop":"bank7-card3.jpg",
                "scroll": "0",
                "bankname":"光大",
                "id":3,
                "link":"https://xyk.cebbank.com/icip/icip-applypage/info1?cardId=24016&pro_code=ZHTG03BKRK000001VISA"
            }
        ]
    },
    "ms":{
        "bankname":"民生",
        "bankid":"cmbc",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"民生银行",
                "links": "javascript:goCards()"
            },
        ],
        "cards":[
            {
                "image":"img/banks/card/ms01@2x.png",
                "name":"Visa留学生芯片标准白金信用卡",
                "shortname":"Visa留学生<br/>芯片标准白金信用卡",
                "detail":"免首年年费，消费满额后还可免次年年费",
                "pop":"bank6-card2.jpg",
                "scroll": "0",
                "bankname":"民生",
                "link":"https://creditcard.cmbc.com.cn/wsv2/step?encryptStr=RpyKzjTqU49aaWP%2FLTV8Ckvr5LbKye5Re7qZiJsoOVCAp3QAM11WFDQyj3NE%2BKNr0VFFWgSQylVJ%2FsmIjfsCzp9yd0HXzHBfJQK6ubq5Qpwos0wusJiDAsZhrik%2B4kGtvLMnr501Yl%2FsjEwUrys%2BOiYc1hzbmWNMGYXr79ZJsDY%3D&cardId=338&source=WX"
            }
        ]
    },
    "sh":{
        "bankname":"上海银行",
        "bankid":"bos",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"上海银行",
                "links": "javascript:goCards()"
            },
        ],
        "cards":[
            {
                "image":"img/banks/card/sh01@2x.png",
                "name":"Visa全球支付卡（全球版）",
                "shortname":"Visa全球支付卡<br/>（全球版）",
                "detail":"0货币兑换手续费，更有年费优惠礼遇",
                "pop":"bank12-card1.jpg",
                "scroll": "0",
                "bankname":"上海银行 BOS",
                "id":1,
                "link":"https://mbank.bankofshanghai.com/pweixin/static/index.html?_TransactionId=CreditCardApply&_CardType=0300001758"
            },
            {
                "image":"img/banks/card/sh02@2x.png",
                "name":"Visa全球支付卡（海淘版）",
                "shortname":"Visa全球支付卡<br/>（海淘版）",
                "detail":"0货币兑换手续费，更有年费优惠礼遇",
                "pop":"bank12-card2.jpg",
                "scroll": "0",
                "bankname":"上海银行 BOS",
                "id":2,
                "link":"https://mbank.bankofshanghai.com/pweixin/static/index.html?_TransactionId=CreditCardApply&_CardType=0300001756"
            }
        ]
    },
    "zd":{
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"渣打银行",
                "links": "javascript:goCards()"
            },
        ],
        "cards":[
            {
                "image":"img/banks/card/zd01@2x.png",
                "name":"Visa臻程卡",
                "shortname":"Visa臻程卡",
                "detail":"现在开卡完成指定消费，即可获得迎新好礼，还有机会免次年年费",
                "pop":"bank13-card1.jpg",
                "scroll": "0",
                "id":1,
                "bankname":"渣打银行 SCB"
            },
            {
                "image":"img/banks/card/zd02@2x.png",
                "name":"Visa真逸卡",
                "shortname":"Visa真逸卡",
                "detail":"现在开卡完成指定消费，即可获得迎新好礼，还有机会免次年年费",
                "pop":"bank13-card2.jpg",
                "scroll": "0",
                "bankname":"渣打银行 SCB",
                "id":2
            }
        ]
    },
    "jx":{
        "bankname":"交行",
        "bankid":"bocom",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"交通银行",
                "links": "javascript:goCards()"
            },
        ],
    },
    "zh":{
        "bankname":"招商银行",
        "bankid":"cmb",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"招商银行",
                "links": "javascript:goCards()"
            },
        ],
        "cards":[
            {
                "image":"img/banks/card/zh01@2x.png",
                "name":"Visa留学信用卡（附卡）",
                "shortname":"Visa留学信用卡（附卡）",
                "detail":"现在申请，有效期内免年费。境外取现，每月前4笔免手续费",
                "pop":"bank4-card1.jpg",
                "bankname":"招行",
                "id":1,
                "link":"https://market.cmbchina.com/ccard/wap/lxswap/lxsfm/more.html"
            },
            {
                "image":"img/banks/card/zh02@2x.png",
                "name":"Visa外币单标信用卡",
                "shortname":"Visa外币单标信用卡",
                "detail":"有效期内无附加条件免年费。全球任意外币消费，人民币记账还款",
                "pop":"bank4-card2.jpg",
                "bankname":"招行",
                "id":2,
                "link":"https://ccclub.cmbchina.com/mca/Oapply.aspx?cardsel=7602"
            },
            {
                "image":"img/banks/card/zh03@2x.png",
                "name":"Visa外币单标白金信用卡",
                "shortname":"Visa外币单标白金信用卡",
                "detail":"限时申请免年费，全球任意外币消费，0外汇兑换费",
                "pop":"bank4-card3.jpg",
                "bankname":"招行",
                "id":3,
                "link":"https://market.cmbchina.com/ccard/wap/qbbwap/index.html"
            }
        ]
    },
    "xy":{
        "bankname":"兴业",
        "bankid":"cib",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"兴业银行",
                "links": "javascript:goCards()"
            },
        ],
        "cards":[
            {
                "image":"img/banks/card/xy01@2x.png",
                "name":"全币种国际信用卡（Visa单品牌）",
                "shortname":"全币种国际信用卡<br/>（Visa单品牌）",
                "detail":"免收国外交易汇兑手续费，全球任意外币消费，人民币记账还款",
                "pop":"bank14-card1.jpg",
                "scroll": "0",
                "bankname":"兴业",
                "id":1,
                "link":"https://wm.cib.com.cn/html/webapp/fast-issue-con/parnter.html?id=03b1333e21aa49cc83959b9015d015c3&from=singlemessage"
            }
        ]
    },
    "zx":{
        "bankname":"中信",
        "bankid":"citic",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"中信银行",
                "links": "javascript:goCards()"
            },
        ],
        "cards":[
            {
                "image":"img/banks/card/zx05@2x.png",
                "name":"Visa Signature 信用卡（御玺卡）",
                "shortname":"Visa Signature<br/>信用卡（御玺卡）",
                "detail":"12月31日前申请，有效期内免年费",
                "pop":"bank5-card1.jpg",
                "scroll": "0",
                "bankname":"中信",
                "id":1,
                "link":"https://cs.creditcard.ecitic.com/citiccard/cardshopcloud/standardcard-h5/index.html?pid=CS0136&cls=SJWXFBK2&sid=SJWXFBK2"
            },
            {
                "image":"img/banks/card/zx01@2x.png",
                "name":"Visa出国留学生信用卡金卡（主卡）",
                "shortname":"Visa出国留学生<br/>信用卡金卡（主卡）",
                "detail":"&nbsp;",
                "pop":"bank5-card2.jpg",
                "scroll": "0",
                "bankname":"中信",
                "id":2,
                "link":"https://cs.creditcard.ecitic.com/citiccard/cardshopcloud/standardcard-h5/index.html?sid=SJWAPPT&pid=CS0090#/baseInfo?t=1582018307834&t=1582018337069&t=1597220402205"
            },
            {
                "image":"img/banks/card/zx02@2x.png",
                "name":"Visa出国留学生信用卡金卡（附属卡）",
                "shortname":"Visa出国留学生<br/>信用卡金卡（附属卡）",
                "detail":"&nbsp;",
                "pop":"bank5-card3.jpg",
                "scroll": "0",
                "bankname":"中信",
                "id":3,
                "link":"https://cs.creditcard.ecitic.com/citiccard/cardshopcloud/standardcard-h5/index.html?sid=SJWAPPT&pid=CS0090#/baseInfo?t=1582018307834&t=1582018337069&t=1597220421496"
            },
            {
                "image":"img/banks/card/zx03@2x.png",
                "name":"Visa出国留学生信用卡白金卡（主卡）",
                "shortname":"Visa出国留学生<br/>信用卡白金卡（主卡）",
                "detail":"&nbsp;",
                "pop":"bank5-card4.jpg",
                "scroll": "0",
                "bankname":"中信",
                "id":4,
                "link":"https://cs.creditcard.ecitic.com/citiccard/cardshopcloud/standardcard-h5/index.html?sid=SJWAPPT&pid=CS0090#/baseInfo?t=1582018307834&t=1582018337069&t=1597220481813"
            },
            {
                "image":"img/banks/card/zx04@2x.png",
                "name":"Visa出国留学生信用卡白金卡（附属卡）",
                "shortname":"Visa出国留学生<br/>信用卡白金卡（附属卡）",
                "detail":"&nbsp;",
                "pop":"bank5-card5.jpg",
                "scroll": "0",
                "bankname":"中信",
                "id":5,
                "link":"https://cs.creditcard.ecitic.com/citiccard/cardshopcloud/standardcard-h5/index.html?sid=SJWAPPT&pid=CS0090#/baseInfo?t=1582018307834&t=1582018337069&t=1597220460609"
            },
            {
                "image":"img/banks/card/zx06@2x.png",
                "name":"国航携程联名<br/>信用卡御玺卡",
                "shortname":"国航携程联名<br/>信用卡御玺卡",
                "detail":"&nbsp;",
                "pop":"bank5-card6.jpg",
                "bankname":"中信",
                "id":6,
                "link":"https://cs.creditcard.ecitic.com/citiccard/cardshopcloud/standardcard-h5/index.html?sid=YDKHD&pid=CS0650"
            },
            {
                "image":"img/banks/card/zx07@2x.png",
                "name":"国航携程联名<br/>信用卡金卡",
                "shortname":"国航携程联名<br/>信用卡金卡",
                "detail":"&nbsp;",
                "pop":"bank5-card7.jpg",
                "bankname":"中信",
                "id":7,
                "link":"https://cs.creditcard.ecitic.com/citiccard/cardshopcloud/standardcard-h5/index.html?sid=YDKHD&pid=CS0649"
            },
            {
                "image":"img/banks/card/zx08@2x.png",
                "name":"Visa 逍遥卡",
                "shortname":"Visa 逍遥卡",
                "detail":"&nbsp;",
                "pop":"bank5-card8.jpg",
                "bankname":"中信",
                "id":8,
                "link":"https://creditcard.ecitic.com/h5/shenqing/xiaoyaoka/index.html?cls=wx&sid=SJWXBKDT1"
            },
        ]
    },
    "jh_debit":{
        "bankname":"建行Debit",
        "bankid":"ccbji",
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"建设银行",
                "links": "javascript:goCards()"
            },
        ],
        "cards":[
            {
                "image":"img/banks/card/jh_debit01@2x.png",
                "name":"Visa标准借记卡",
                "shortname":"Visa标准借记卡",
                "detail":"现在办卡，即可收获超低收费与超值惠享",
                "pop":"bank8-card1.jpg",
                "scroll": "0",
                "id":1,
                "bankname":"建行 Debit"
            },
            {
                "image":"img/banks/card/jh_debit02@2x.png",
                "name":"Visa金借记卡",
                "shortname":"Visa金借记卡",
                "detail":"现在办卡，即可收获超低收费与超值惠享",
                "pop":"bank8-card2.jpg",
                "scroll": "0",
                "id":2,
                "bankname":"建行 Debit"
            },
            {
                "image":"img/banks/card/jh_debit03@2x.png",
                "name":"Visa白金借记卡",
                "shortname":"Visa白金借记卡",
                "detail":"现在办卡，即可收获超低收费与超值惠享",
                "pop":"bank8-card3.jpg",
                "scroll": "0",
                "bankname":"建行 Debit"
            },
            {
                "image":"img/banks/card/jh_debit04@2x.png",
                "name":"Visa无限借记卡",
                "shortname":"Visa无限借记卡",
                "detail":"现在办卡，即可收获超低收费与超值惠享",
                "pop":"bank8-card4.jpg",
                "scroll": "0",
                "id":3,
                "bankname":"建行 Debit"
            }
        ]
    },
    "xdf":{
    },
    "nh_debit":{
        "banners":[
            {
                "image":"img/top_banner/s1-banner1.jpg",
                "desc":"农业银行",
                "links": "javascript:goCards()"
            },
            {
                "image":"img/banks/top_banner/bank_nh_debit@2x.png",
                "desc":"农行借记卡",
            }
        ],
        "cards":[
            {
                "image":"img/banks/card/nh01@2x.png",
                "name":"留学白金信用卡（美好生活版）",
                "shortname":"留学白金信用卡<br/>（美好生活版）",
                "detail":"刷卡免国际结算费，更可享1元起境外接送机福利",
                "pop":"bank2-card1.jpg",
                "scroll": "0",
                "bankname":"农行",
                "id":1,
                "link":"https://wx.abchina.com/CreditCard/netBank/webank/applyCard.aspx?id=null&q=direct&cardcode=VCPC1I"
            },
            {
                "image":"img/banks/card/nh02@2x.png",
                "name":"留学白金信用卡（诗情画意版）",
                "shortname":"留学白金信用卡<br/>（诗情画意版）",
                "detail":"刷卡免国际结算费，更可享1元起境外接送机福利",
                "pop":"bank2-card2.jpg",
                "scroll": "0",
                "bankname":"农行",
                "id":2,
                "link":"https://wx.abchina.com/CreditCard/netBank/webank/applyCard.aspx?id=null&q=direct&cardcode=VCPC1I"
            }
        ]
    }
}